### ISSUE TITLE
Missing country

### ISSUE THREAD

**Issue by hervino14** [joielechong/CountryCodePicker#1]
This is a cool library but there is some mistakes with some countries.
Your library has the same Congo repeat twice. There are two Congo in the world 
[D.R.Congo](https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo) and [Congo](https://en.wikipedia.org/wiki/Republic_of_the_Congo)

Best regards

**Comment by joielechong** [comment]
Thank you for reporting @hervino14!

I've update the country in the 1.8.0 version. Please check the library.

I'll close this issue. Please reopened it again if the problem still persist.
