### ISSUE TITLE
Sometimes it's crashed during inflation from xml.

### ISSUE THREAD

**Issue by dlykoits** [joielechong/CountryCodePicker#12]
java.lang.NullPointerException CountryCodePicker.java line 343 in CountryCodePicker.setSelectedCountry()
Attempt to invoke virtual method 'java.lang.String com.rilixtech.Country.getIso()' on a null object reference
com.rilixtech | CountryCodePicker.java line 343 in CountryCodePicker.setSelectedCountry()
com.rilixtech | CountryCodePicker.java line 772 in CountryCodePicker.setCountryForNameCode()
me.runningcoach.ui.activities | SWControlActivity.java line 131 in SWControlActivity.showPhoneDialog()

**Comment by anupsunni** [comment]
Same Problem Here.

**Comment by anupsunni** [comment]
Please Let me know if you find a solution.

**Comment by joielechong** [comment]
I can't reproduce the problem. I'll close the issue for now. Please reopen if the issue still persist.
