### ISSUE TITLE
Country data is not updated 

### ISSUE THREAD

**Issue by srb9181** [joielechong/CountryCodePicker#19]
many country like south sudan, kosova not added in lib. please add their country std codes and corresponding flags.

**Comment by joielechong** [comment]
Thank you for your suggestion. I really sorry because I can't regularly update this library. If you have time, please send PR for adding another country flags and value.

**Comment by srb9181** [comment]
I have created Pull Request. Please check and verify .

**Comment by joielechong** [comment]
Thank you for the PR!
