### ISSUE TITLE
Failed to resolve: com.github.joielechong:countrycodepicker:2.1.6

### ISSUE THREAD

**Issue by iamsarker** [joielechong/CountryCodePicker#20]
Error:(34, 20) Failed to resolve: com.github.joielechong:countrycodepicker:2.1.6
<a href="openFile:/home/sarker/AYS/AysUser/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by joielechong** [comment]
Please try using the latest version: 2.1.8

**Comment by Akhrorjon** [comment]
@joielechong thansk for updates) is it possible to customize the string: select_country 
![inkedscreenshot_2018-04-23-14-24-00_li](https://user-images.githubusercontent.com/22519041/39118216-4a836260-4702-11e8-9148-9c39d0fc653a.jpg)

**Comment by joielechong** [comment]
I think this should be closed. @Akhrorjon: I've answering your question in issue #18. So, I'll close this issue then ;)
