### ISSUE TITLE
country picker crashes in android tv

### ISSUE THREAD

**Issue by abrahamgjk** [joielechong/CountryCodePicker#23]
android tv uses leanback and extends activity

**Comment by joielechong** [comment]
Wow, I never thought this library will be used for Android TV project so I never test it in Android TV. 

How the step to reproduce the crashes? I will check the problem asap.

**Comment by joielechong** [comment]
The library now working on Android TV. Tested with Android TV Api 22. Please take a look for the sampletv in the project.
