### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by egek92** [joielechong/CountryCodePicker#24]
I want to localize only the "select country " and "search" texts to my own language(Turkish), can I make pull request after I change the string resources

**Comment by joielechong** [comment]
If you only want to Turkish for `select country` and `search`, you can override the text by adding the following string to your `strings.xml` resource (the text is only a sample, I don't expect it as a right translation :D) :

```
  <string name="search_hint">Arama&#8230;</string>
  <string name="select_country">Ülke Seç</string>
```

Be noted that it will only override the language for English locale.

For the pull request, I really glad if you can provide the whole translation of the library ;)
