### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by 2math** [joielechong/CountryCodePicker#27]
Hi,
I'm testing your library in one of my projects and it looks good until I had to make a production build :) .
I have a really hard time to deobfuscate the build with proguard after the library was added.
Do you have any progruard rules to suggest ?

**Comment by joielechong** [comment]
You don't need to use any proguard rule for the project. I have one project currently with this library in production and use proguard too. Have you check if you've another library not working with the proguard?

**Comment by joielechong** [comment]
What happens when you use the `2.1.8` version? Seems like I forgot to update the documentation.

**Comment by 2math** [comment]
I'm working tomorrow on this project and will check and let you know

**Comment by 2math** [comment]
with v2.1.8 works :)

**Comment by joielechong** [comment]
Great! Sorry for not updating the documentation.. :(
