### ISSUE TITLE
Error setting registered Phone Number TextView

### ISSUE THREAD

**Issue by jrodriguezva** [joielechong/CountryCodePicker#28]
At line 311 you call _setRegisteredPhoneNumberTextView_ and pass _mTvSelectedCountry_ as an edittext. In this function you initialize your _mRegisteredPhoneNumberTextView_ variable with the textview parameter, this causes that when you call _getFullNumber_ or _setFullNumber_, the number obtained or set is erroneous.

You can see it in your sample at FullNumberFragment when you click buttonLoadNumber and load the text of editTextLoadFullNumber to CPP

**Comment by joielechong** [comment]
Thank you very much for the finding! I'll fix this bug!

**Comment by ShabanKamell** [comment]
Hey all,
@joielechong 
Why didn't fix the bug?

**Comment by joielechong** [comment]
@ShabanKamell: the bug is now fixed. Previously I have too many task to do in my current project, hence I can't promptly update the library. I'm sorry for that.

Issue is fixed on https://github.com/joielechong/CountryCodePicker/commit/6a080bf86375b195d6b6f4af34cd2d38e5c83f81
