### ISSUE TITLE
hint problem... extra digit that confuses users

### ISSUE THREAD

**Issue by Mirmuhsin** [joielechong/CountryCodePicker#32]
Hint shows extra digit that is supposed to be in the country code.
Example... 
Country Code: **(TR) +90**
Hint: **05012345678**
So when combined: +90 05012345678. The problem is there are 2 zeros. Actual Turkish numbers are +905012345678 like this. It confuses the user when typing their phone number.
Hints for other countries should also be checked.

**Comment by AlekseyMak** [comment]
+1 For Russian numbers. 
Hint is 8 (916) 123-45-67
But we already have country code +7 and this digit 8 does not needed. 

Suggested a setting to disable hints

**Comment by joielechong** [comment]
Thank for the issue! And sorry for my late response and laziness.

This library is depend on https://github.com/MichaelRocks/libphonenumber-android library. Nothing I can do with the problem right now :( . Could you guys create an issue there?

**Comment by joielechong** [comment]
I'll close this issue for now.
