### ISSUE TITLE
how to get phoneCode without listener

### ISSUE THREAD

**Issue by Asykur** [joielechong/CountryCodePicker#33]
is it possible to take phone code without listener?

**Comment by jstr14** [comment]
Hello Askyur as you can read on README you can get phone code using:

- getSelectedCountryCode(); method. => “91”
- getSelectedCountryCodeWithPlus(); method. => “+91”
- getSelectedCountryCodeAsInt(); method. => 91

I hope I've helped

**Comment by Asykur** [comment]
thanks, it's work

**Comment by joielechong** [comment]
Thank you for helping @jstr14 :+1:
