### ISSUE TITLE
callOnClick() or performClick() method is not working 

### ISSUE THREAD

**Issue by vishalroygeek** [joielechong/CountryCodePicker#37]
When trying to use `callOnClick();` or `performClick()` method in CCP, its not working. But working fine with other views

**Comment by joielechong** [comment]
CountryCodePicker is comprised from multiple views. The two main views are: Flag view and Phone Number view. Which one did you one to call the `callOnClick` or `performClick()`? I'll try to add the method click handler for your specific case.

**Comment by vishalroygeek** [comment]
Actually, the click methods aren't important. I was looking for a method through which I can show the country picker dialog, without clicking that button. I wanted the CCP in my settings screen. So I created CCP view, made it hidden and performed the click. And it didn't work. So, for this I was looking for that feature. It would be great if you add something like - `ccp.showCountryPickerDialog()`

**Comment by joielechong** [comment]
Sorry for the 1 year late response...:(.

I've updated the library and add the showCountryPickerDialog() method in https://github.com/joielechong/CountryCodePicker/commit/1d9ac17504da3ef510eecaf7c34b45388cce5391 commit. I'll close this issue for now.
