### ISSUE TITLE
some characters producing illegal character encoding when building project

### ISSUE THREAD

**Issue by abba-maker** [joielechong/CountryCodePicker#4]
I added the library, everything worked fine, but app wont build because some charaters like the fancy o in cote_d_ivoire are producing error: unmappable character for encoding utf-8 and error: illegal character encoding.

**Comment by joielechong** [comment]
I've also experience the same error in previous version. Let me update the code to handle this issue.

**Comment by joielechong** [comment]
@abba-maker: I've updated the code and fixing the illegal character error. Please try the 2.1.1 version. ;)

**Comment by abba-maker** [comment]
@joielechong OK cool, I'll try it out and let you know how it goes

**Comment by joielechong** [comment]
@abba-maker: I've update the code with 2.1.2 version. Now CCP can be shown in Layout Editor!

**Comment by joielechong** [comment]
@abba-maker: I'll close this issue, I expected that the problem is solved. Feel free to reopen this issue if the problem still persist.
