### ISSUE TITLE
Only want to show flag

### ISSUE THREAD

**Issue by Mehdi-android** [joielechong/CountryCodePicker#41]
Hello, this is awesome library. Only problem is now i only want to show flag and nothing else.

**Comment by joielechong** [comment]
Sorry for late response and my laziness.. :(.

Now you can use `app:ccp_hidePhoneCode="true"` and  attribute to hide the phone number.

`  <com.rilixtech.widget.countrycodepicker.CountryCodePicker
      android:id="@+id/ccp"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      app:ccp_hideNameCode="true"
      app:ccp_hidePhoneCode="true"
      />`

**Comment by joielechong** [comment]
Please use version 2.4.1
