### ISSUE TITLE
Brazilian phone numbers not formatted correctly

### ISSUE THREAD

**Issue by BrilliantCorp** [joielechong/CountryCodePicker#43]
For instance, if I enter the number 11 3209-6622, where 11 is the area code for São Paulo, Brazil's largest city, your device will format it as 1132-096-622. I understand it if you don't have the time to make sure every country's phone numbers are formatting correctly, so is there a way for users to modify the device to make sure the countries they need are formatting correctly?

**Comment by joielechong** [comment]
I'm sorry for the late response and my laziness.. :(

That's probably a bug from the previous version or the libphone-number didn't support it yet. Can you confirm if it still persist in version 2.4.0?

**Comment by joielechong** [comment]
I'll close this isssue for now.
