### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by GotaloveCode** [joielechong/CountryCodePicker#44]
Hi.Will there be support release for androidX?

**Comment by joielechong** [comment]
On the next release I'll try to remove the support libraries from the dependencies so it won't depends on either support library or androidX. If that can't be achieved, I guess the newest library will be using androidX.

**Comment by joielechong** [comment]
@GotaloveCode: All support libraries has been removed from https://github.com/joielechong/CountryCodePicker/releases/tag/2.3.0 version. This version should be working in AndroidX.

**Comment by GotaloveCode** [comment]
Noted.Awesome work on this Library.Thank you for sharing and supporting
this project.
