### ISSUE TITLE
ArrayIndexOutOfBoundsException in CountryCodeDialog.java

### ISSUE THREAD

**Issue by devenpawar18** [joielechong/CountryCodePicker#45]
One of our user had following crash:

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsExceptionlength=303; index=-1 Raw Text
--
  | java.util.ArrayList.get (ArrayList.java:310)
  | com.rilixtech.CountryCodeDialog$ItemRecyclerViewClickListener.onClick (CountryCodeDialog.java:204)
  | android.view.View.performClick (View.java:4780)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:698)
```

On checking Crashlytics, I found the device `GI I9500 TMMARS` running Android `5.1`. 
On some investigation I found some insight about such devices [here](https://stackoverflow.com/questions/34942269/downloadmanager-illegalstateexception-creating-a-download-in-directory-downloads)

Could you check if this is a genuine issue & fix it or its something because `TMMARS` is blocking something by detecting some threat.

Thanks

**Comment by joielechong** [comment]
That should be the problem like the in the linked SO question. It probably not the library problem. 

I simply can't reproduce the crash at all in some of our 5.1 devices. One of my project using this library but never get the report about such crash.

Is it only happened on a single user device?

**Comment by devenpawar18** [comment]
Yes currently the crash occurred only once. I don't have Android 5.1 device but I tested on emulators & couldn't reproduce the crash too.

But just for safety, is it possible to add a check around `itemPosition` (line no 204) in CountryCodeDialog.java verifying its greater than `0`?

Thanks

**Comment by joielechong** [comment]
That is possible. Let me update the code. Probably tomorrow.

**Comment by joielechong** [comment]
I've update the code. Please test the release tag 2.3.1

**Comment by devenpawar18** [comment]
That helps. Thanks again

**Comment by devenpawar18** [comment]
@joielechong
I checked the condition. The following condition is only checking the upper bound of the list.

if(mFilteredCountries.size() < position) {
        Log.e(TAG, "Something wrong with the ListView. Please report this!");
        return;
      }
Since in my crash, the index was -1, could you update it to cover both upper & lower bounds? Something like

if(mFilteredCountries.size() < position || position < 0) {
        Log.e(TAG, "Something wrong with the ListView. Please report this!");
        return;
      }

**Comment by joielechong** [comment]
@devenpawar18: That's totally correct! I've missed that part. Thank you!, will update it later

**Comment by joielechong** [comment]
I've update the code with the changes. You can use the 2.3.2 version. Sorry, for the late update.

**Comment by devenpawar18** [comment]
Thanks @joielechong
