### ISSUE TITLE
ERROR: Failed to resolve: com.github.joielechong:countrycodepicker:2.3.0

### ISSUE THREAD

**Issue by Jeevacse07** [joielechong/CountryCodePicker#51]
this is included in build.gradle
repositories {
            google()
            jcenter()
            maven { url "https://jitpack.io" }
    }

but still getting the above error

**Comment by joielechong** [comment]
Please try using 2.3.3

**Comment by Jeevacse07** [comment]
i made mistake by putting it in wrong repositories.
now i got that fixed
