### ISSUE TITLE
setDefaultCountryUsingNameCode() not working

### ISSUE THREAD

**Issue by ShehryarZaheer** [joielechong/CountryCodePicker#56]
I am using setDefaultCountryUsingNameCode("US") but still getting Pakistan +92 as the default country. Can someone advise what I may be doing wrong or is it a bug?

**Comment by mapm14** [comment]
Same here ✋.

**Comment by tahafarooqui** [comment]
You need resetToDefaultCountry(); function after setDefaultCountryUsingNameCode();

Example:
        nationality.setDefaultCountryUsingNameCode("US");
        nationality.resetToDefaultCountry();

**Comment by joielechong** [comment]
Thanks @tahafarooqui! We need to call `resetToDefaultCountry()` after calling `setDefaultCountryUsingNameCode()` as in the method documentation.

@All: I think I should add a more readable for setting the default country, something like:
`setDefaultCountryUsingNameCodeAndApply("US");`
how do you think?

**Comment by mapm14** [comment]
I think it's a great idea @joielechong 👍, make it into two steps (like currently) can confuse some people.

**Comment by tahafarooqui** [comment]
@joielechong Yes, Please. That would be great.

**Comment by joielechong** [comment]
The method has been added in https://github.com/joielechong/CountryCodePicker/commit/8b9cd80b590c1e09920ba7c30b91d4c618af4cc8 commit. But I haven't test it yet.

**Comment by joielechong** [comment]
All the related changes has been included in https://github.com/joielechong/CountryCodePicker/releases/tag/2.4.1.
