### ISSUE TITLE
set layout direction

### ISSUE THREAD

**Issue by sadeghpro** [joielechong/CountryCodePicker#69]
how to set layout direction to ltr
UI on api 17 with rtl direction is some buggy then I want set layout direction to be always ltr

![device-2019-11-06-135444](https://user-images.githubusercontent.com/22843329/68290355-10cda700-009d-11ea-9fe8-feeb770993cb.png)

**Comment by joielechong** [comment]
Solved by @sadeghpro PR. Thanks!
