### ISSUE TITLE
Separate text color for view and dialog

### ISSUE THREAD

**Issue by alpex92** [joielechong/CountryCodePicker#7]
When you set app:ccp_textColor property to white, you will have white labels on white background in dialog. Any workarounds?

**Comment by joielechong** [comment]
Currently, there is no workarouds. But I can add an attribute to set the color of the dialog. Something like app:ccp_textColorDialog. How do you think about it?

Any suggestion?

**Comment by alpex92** [comment]
Yeah it would be great. Thanks!

**Comment by joielechong** [comment]
I've added `ccp_dialogTextColor` to change dialog text color. Please use 2.1.5 version.

**Comment by joielechong** [comment]
I'll close this issue for now, please reopen if the problem still persist.
