### ISSUE TITLE
Showing only Default Country code in Dialog

### ISSUE THREAD

**Issue by YogeshLegendkiller** [joielechong/CountryCodePicker#71]
Hi  First i must say This is a fantastic library, my query is  am new version of the library 
   **implementation 'com.github.joielechong:countrycodepicker:2.4.1'**

while using this am getting only default country code like in this image i have attached below can you help me on this.
![IMG_20191122_003810 375](https://user-images.githubusercontent.com/23256867/69368588-6ff80200-0cc0-11ea-9186-9a44da8bf222.png)

**Comment by joielechong** [comment]
Probably you've already fixed the problem because of my late response. Sorry for that.
Please reopen this issue if you have further question for the problem.
