### ISSUE TITLE
Getting wrong country code for North Korea

### ISSUE THREAD

**Issue by niravtopsy** [joielechong/CountryCodePicker#72]
I am implemented same library but, this library showing same country code for Antarctica ( AQ ) +672
and same country code for North Korea ( KP ) +672, Actually North Korea have +850 country code,
Please resolve this and update library.

**Comment by joielechong** [comment]
Sorry for the super super late response.

This bugs is fixed with https://github.com/joielechong/CountryCodePicker/commit/076f3b84e283df0cb48593cdccb84342edf4c392 commit.

**Comment by niravtopsy** [comment]
Thanks :)
