### ISSUE TITLE
Phone Number Auto Formatted

### ISSUE THREAD

**Issue by Alejan93** [joielechong/CountryCodePicker#8]
Why the phone number auto formatted only works when I set a default country code in the .xml, but if I select another country the phone number doesn't get formatted

**Comment by joielechong** [comment]
This is is fixed in https://github.com/joielechong/CountryCodePicker/commit/6a080bf86375b195d6b6f4af34cd2d38e5c83f81 commit.

**Comment by jishindev** [comment]
Still happening in 2.3.0
