### ISSUE TITLE
Palestine country not found in the CountryCodePicker

### ISSUE THREAD

**Issue by MohammedHassouna** [joielechong/CountryCodePicker#9]
When I use the CountryCodePicker library,
not found Palestine country in the CountryCodePicker
https://en.wikipedia.org/wiki/Palestinian_territories
We are occupied by Israel
and our CountryCode is 970
So please add our CountryCode to your library

**Comment by MohammedHassouna** [comment]
The Country Code is not added ??

**Comment by joielechong** [comment]
I'm very sorry. I always avoid all related with political correctness. As for the Palestine country, it still not recognized as sovereign country. Hence I avoid to be caught in political problem by not adding Palestine flag. 

Of course you can fork this library and add the country.

**Comment by MohammedHassouna** [comment]
This is not political correctness, google and facebook or other ...etc add the Palestine code
For example, Google customize domain for Palestine: https://www.google.ps/
In the end, That's up to you if you add it or not.
